### ISSUE TITLE
Release article for Release 0.1

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#165] opened 2015-02-09 15:50 UTC
We need a slightly more detailed release article for Release 0.1. It should contain some of the less well-known features:

**Disaster recovery**
* you lose your password - click Restore on credentials screen and recover it from local backup with your "wallet words" (seed phrase)
* you delete all your local backups (simulate hard drive error) - observe automatic restore from cloud backup
* you delete all your local and cloud backups (simulate stolen laptop) - select "Restore from wallet words" and follow the instructions
* you forget your wallet words - unlock your firesafe and retrieve the laminated paper copy you made
* you lose your Trezor - restore the Trezor wallet from your "wallet words" and move the bitcoin to safety

**Privacy**
* TOR support
* Trezor support - private keys not held on desktop machine
* SPV mode - no additional servers
* our privacy policy
* all data stored encrypted and remains local to your machine (no uploading to our servers)
* balance header can be hidden when out in public

**Contacts**
* searchable contact list
* add tags and private notes with multi-select
* contact details remain encrypted and private to your machine

**Convenience**
* support for Payment Protocol (BIP 70) to make online purchases quicker and safer
* simple and familiar installation process for Windows, Mac and Linux
* one-click copy-paste to sign or verify "Bitcoin signed" messages
* empty your wallet to a single address and have all fees calculated automatically
* change the units to suit your tastes ("bits", ecogex symbol etc)
* range of Bitcoin exchanges
* light and dark themes 
* no plugins to install - it's all out of the box

**Transactions**
* searchable payments list
* clear display of transaction status
* drill down to details

Overall, this is a wallet that is suitable for mainstream users.

**Comment by jim618** [comment] 2015-05-18 11:54
Dupe of #192 so closing

**Closed by jim618** 2015-05-18 11:54 UTC
